const emojipedia = [
  { id: 1, emoji: "💪", name: "Tense Biceps", meaning: "You can do that! or I feel strong! Arm with tense biceps. Also used in connection with doing sports, e.g. at the gym." },
  { id: 2, emoji: "🙏", name: "Person With Folded Hands", meaning: "Two hands pressed together. Used for prayer, gratitude, or a high five." },
  { id: 3, emoji: "🤣", name: "Rolling On The Floor, Laughing", meaning: "A smiley face, rolling on the floor, laughing uncontrollably." },
  { id: 4, emoji: "😎", name: "Smiling Face With Sunglasses", meaning: "Cool, relaxed, or confident attitude." },
  { id: 5, emoji: "😇", name: "Smiling Face With Halo", meaning: "Represents innocence, kindness, or holiness." },
  { id: 6, emoji: "🤔", name: "Thinking Face", meaning: "Used to indicate thinking, curiosity, or doubt." },
  { id: 7, emoji: "😍", name: "Smiling Face With Heart-Eyes", meaning: "Expresses love, admiration, or enthusiasm." },
  { id: 8, emoji: "😢", name: "Crying Face", meaning: "Represents sadness, pain, or disappointment." },
  { id: 9, emoji: "😡", name: "Pouting Face", meaning: "Used to show anger or frustration." },
  { id: 10, emoji: "🤯", name: "Exploding Head", meaning: "Represents shock, amazement, or a mind-blowing realization." },
  { id: 11, emoji: "🤗", name: "Hugging Face", meaning: "A friendly smiley giving a hug." },
  { id: 12, emoji: "😴", name: "Sleeping Face", meaning: "Indicates sleepiness or boredom." },
  { id: 13, emoji: "😷", name: "Face With Medical Mask", meaning: "Represents illness or concern for hygiene." },
  { id: 14, emoji: "🤮", name: "Face Vomiting", meaning: "Used to show extreme disgust." },
  { id: 15, emoji: "💀", name: "Skull", meaning: "Represents death, danger, or something extremely funny." },
  { id: 16, emoji: "🎉", name: "Party Popper", meaning: "Used for celebrations and special occasions." },
  { id: 17, emoji: "🔥", name: "Fire", meaning: "Represents something hot, cool, or trending." },
  { id: 18, emoji: "💯", name: "Hundred Points", meaning: "Indicates something is 100% or perfect." },
  { id: 19, emoji: "🚀", name: "Rocket", meaning: "Symbolizes fast progress or a big launch." },
  { id: 20, emoji: "🎯", name: "Bullseye", meaning: "Represents precision or achieving a goal." },
  { id: 21, emoji: "🤩", name: "Star-Struck", meaning: "Shows amazement or admiration." },
  { id: 22, emoji: "🙄", name: "Face With Rolling Eyes", meaning: "Expresses sarcasm or annoyance." },
  { id: 23, emoji: "🥶", name: "Cold Face", meaning: "Indicates extreme cold or shock." },
  { id: 24, emoji: "🤡", name: "Clown Face", meaning: "Used to represent foolishness or clownish behavior." },
  { id: 25, emoji: "👀", name: "Eyes", meaning: "Used to indicate looking, interest, or suspicion." },
  { id: 26, emoji: "💡", name: "Light Bulb", meaning: "Represents an idea or inspiration." },
  { id: 27, emoji: "🎵", name: "Musical Note", meaning: "Used for music, rhythm, or sound." },
  { id: 28, emoji: "🍕", name: "Pizza", meaning: "Represents food, cravings, or Italian cuisine." },
  { id: 29, emoji: "☕", name: "Hot Beverage", meaning: "Symbolizes coffee, tea, or warmth." },
  { id: 30, emoji: "🏆", name: "Trophy", meaning: "Represents victory, achievement, or success." },
  { id: 31, emoji: "📅", name: "Calendar", meaning: "Indicates scheduling or an important date." },
  { id: 32, emoji: "📌", name: "Pushpin", meaning: "Used for marking something important." },
  { id: 33, emoji: "🔒", name: "Locked", meaning: "Represents security, privacy, or confidentiality." },
  { id: 34, emoji: "❤️", name: "Red Heart", meaning: "Expresses love, passion, or deep affection." },
  { id: 35, emoji: "💔", name: "Broken Heart", meaning: "Represents heartbreak or emotional pain." },
  { id: 36, emoji: "🐶", name: "Dog Face", meaning: "Represents a pet dog or cuteness." },
  { id: 37, emoji: "🐱", name: "Cat Face", meaning: "Represents a pet cat or playfulness." },
  { id: 38, emoji: "🦊", name: "Fox Face", meaning: "Represents cleverness, cunning, or playfulness." },
  { id: 39, emoji: "🐻", name: "Bear Face", meaning: "Symbolizes warmth, protection, or wildness." },
  { id: 40, emoji: "🐼", name: "Panda Face", meaning: "Represents cuteness, gentleness, or laziness." },
  { id: 41, emoji: "🌍", name: "Globe Showing Europe-Africa", meaning: "Represents the world, earth, or environment." },
  { id: 42, emoji: "🌞", name: "Sun With Face", meaning: "Represents warmth, happiness, or a bright day." },
  { id: 43, emoji: "🌙", name: "Crescent Moon", meaning: "Symbolizes nighttime, rest, or dreams." },
  { id: 44, emoji: "⭐", name: "Star", meaning: "Represents excellence, brightness, or space." },
  { id: 45, emoji: "☂️", name: "Umbrella", meaning: "Represents rain, protection, or travel." },
  { id: 46, emoji: "🐸", name: "Frog Face", meaning: "Represents frogs, nature, or a calm attitude." },
  { id: 47, emoji: "🐢", name: "Turtle", meaning: "Symbolizes slowness, patience, or wisdom." },
  { id: 48, emoji: "🐍", name: "Snake", meaning: "Represents danger, cunning, or transformation." },
  { id: 49, emoji: "🐙", name: "Octopus", meaning: "Symbolizes intelligence, flexibility, or the ocean." },
  { id: 50, emoji: "🦑", name: "Squid", meaning: "Used for marine life, adaptability, or mystery." },
  { id: 51, emoji: "🦞", name: "Lobster", meaning: "Represents seafood, strength, or resilience." },
  { id: 52, emoji: "🦜", name: "Parrot", meaning: "Symbolizes talkativeness, intelligence, or tropical vibes." },
  { id: 53, emoji: "🦩", name: "Flamingo", meaning: "Used for elegance, uniqueness, or exotic places." },
  { id: 54, emoji: "🦔", name: "Hedgehog", meaning: "Represents cuteness, protection, or introversion." },
  { id: 55, emoji: "🐿️", name: "Chipmunk", meaning: "Symbolizes playfulness, energy, or hoarding." },
  { id: 56, emoji: "🦦", name: "Otter", meaning: "Used for fun, teamwork, or aquatic life." },
  { id: 57, emoji: "🐋", name: "Whale", meaning: "Represents wisdom, depth, or marine conservation." },
  { id: 58, emoji: "🐬", name: "Dolphin", meaning: "Symbolizes intelligence, playfulness, or the ocean." },
  { id: 59, emoji: "🐠", name: "Tropical Fish", meaning: "Represents exotic fish, aquariums, or the sea." },
  { id: 60, emoji: "🦈", name: "Shark", meaning: "Used for fear, power, or oceanic themes." },
  { id: 61, emoji: "🦓", name: "Zebra", meaning: "Symbolizes uniqueness, adventure, or safari life." },
  { id: 62, emoji: "🦒", name: "Giraffe", meaning: "Represents curiosity, height, or Africa." },
  { id: 63, emoji: "🦘", name: "Kangaroo", meaning: "Used for Australia, energy, or jumping." },
  { id: 64, emoji: "🐉", name: "Dragon", meaning: "Represents power, mythology, or fantasy stories." },
  { id: 65, emoji: "🐲", name: "Dragon Face", meaning: "Symbolizes strength, wisdom, or Eastern cultures." },
  { id: 66, emoji: "🦚", name: "Peacock", meaning: "Used for beauty, pride, or elegance." },
  { id: 67, emoji: "🦢", name: "Swan", meaning: "Represents grace, transformation, or love." },
  { id: 68, emoji: "🐦", name: "Bird", meaning: "Symbolizes freedom, nature, or songbirds." },
  { id: 69, emoji: "🦉", name: "Owl", meaning: "Represents wisdom, night, or mystery." },
  { id: 70, emoji: "🦜", name: "Parrot", meaning: "Used for mimicry, intelligence, or pirates." },
  { id: 71, emoji: "🐕", name: "Dog", meaning: "Represents loyalty, pets, or companionship." },
  { id: 72, emoji: "🐈", name: "Cat", meaning: "Symbolizes independence, mystery, or playfulness." },
  { id: 73, emoji: "🐎", name: "Horse", meaning: "Used for speed, strength, or horse riding." },
  { id: 74, emoji: "🦄", name: "Unicorn", meaning: "Represents fantasy, magic, or uniqueness." },
  { id: 75, emoji: "🐄", name: "Cow", meaning: "Symbolizes farming, dairy, or Hindu culture." },
  { id: 76, emoji: "🐖", name: "Pig", meaning: "Represents farm animals, pork, or wealth in some cultures." },
  { id: 77, emoji: "🦌", name: "Deer", meaning: "Symbolizes grace, nature, or Christmas themes." },
  { id: 78, emoji: "🦇", name: "Bat", meaning: "Used for Halloween, night, or the supernatural." },
  { id: 79, emoji: "🦅", name: "Eagle", meaning: "Represents freedom, strength, or the USA." },
  { id: 80, emoji: "🐝", name: "Bee", meaning: "Symbolizes hard work, nature, or sweetness." },
  { id: 81, emoji: "🦋", name: "Butterfly", meaning: "Used for transformation, beauty, or nature." },
  { id: 82, emoji: "🐞", name: "Ladybug", meaning: "Represents good luck, gardens, or insects." },
  { id: 83, emoji: "🦂", name: "Scorpion", meaning: "Used for danger, mystery, or Scorpio zodiac sign." },
  { id: 84, emoji: "🐛", name: "Bug", meaning: "Represents insects, nature, or transformation." },
  { id: 85, emoji: "🦠", name: "Microbe", meaning: "Symbolizes germs, science, or viruses." },
  { id: 86, emoji: "🍄", name: "Mushroom", meaning: "Represents nature, fantasy, or food." },
  { id: 87, emoji: "🌵", name: "Cactus", meaning: "Symbolizes desert life, resilience, or nature." },
  { id: 88, emoji: "🎄", name: "Christmas Tree", meaning: "Used for holidays, joy, or winter themes." },
  { id: 89, emoji: "🌞", name: "Sun With Face", meaning: "Represents warmth, positivity, or the sky." },
  { id: 90, emoji: "🌛", name: "Crescent Moon Face", meaning: "Symbolizes nighttime, dreams, or relaxation." },
  { id: 91, emoji: "🌈", name: "Rainbow", meaning: "Used for positivity, pride, or weather themes." },
  { id: 92, emoji: "❄️", name: "Snowflake", meaning: "Represents winter, cold, or uniqueness." },
  { id: 93, emoji: "🔥", name: "Fire", meaning: "Used for energy, heat, or something amazing." },
  { id: 94, emoji: "💧", name: "Droplet", meaning: "Symbolizes water, tears, or rain." },
  { id: 95, emoji: "🌊", name: "Ocean Wave", meaning: "Used for beach, surfing, or water themes." },
  { id: 96, emoji: "🌪️", name: "Tornado", meaning: "Represents storms, chaos, or strong winds." },
  { id: 97, emoji: "🌠", name: "Shooting Star", meaning: "Symbolizes wishes, space, or good luck." },
  { id: 98, emoji: "🪐", name: "Ringed Planet", meaning: "Used for space, astronomy, or Saturn." },
  { id: 99, emoji: "💫", name: "Dizzy", meaning: "Represents spinning, stars, or being lightheaded." },
  { id: 100, emoji: "☄️", name: "Comet", meaning: "Symbolizes space, rarity, or astronomical events." }
];



export default emojipedia;